### ISSUE TITLE
Flares are just a plecebo

### ISSUE THREAD

**Issue by TastyDischarge** [A3Armory/ArmA3_Wasteland.Altis#17]
Flares for A/C to defend against AA missiles do not work on your server.

**Comment by mooneymoon** [comment]
https://en.wikipedia.org/wiki/Flare_(countermeasure)#Tactics

Read carefully. Just dumping flares does not work in real life, nor does it work in Arma. It has to be paired with certain movements and even then they are not always effective.
 
If you actually believe something in Wasteland is causing them not to work you need to report it to the main A3Wasteland repository at https://github.com/A3Wasteland as there is no custom code in Armory that would have this effect other than possibly lag.

**Comment by TastyDischarge** [comment]
**READ CAREFULLY** If I thought something was wrong with Wasteland I would have posted there. Perhaps you didn't put on your reading glasses when I stated "your server".

**Comment by Gigatek1** [comment]
Nice to see you're defensive as ever, even when someones trying to help you. Search the mission for anything that could change the way flares work and we'll look into fixing this. From what I've seen of the mission files, there's nothing I can think of. Also try asking AgentRev on someone on the forums. They might have some insight on this issue.

**Comment by TastyDischarge** [comment]
Remember, I like playing. Not administration or coding. If it works on another server then that is where I'll be. BTW, I'm not the only one who believes there is an issue with flares on A3Armory.


Sent from my dumbphone


-------- Original message --------

**Comment by Gigatek1** [comment]
No one wants you to administrate or code anything. Please use the git to report bugs with the code. For conjecture use the forums.
